services:
  backend:
    container_name: mtm-backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env    

  frontend:
    container_name: mtm-frontend
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
